FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY VocaBuddy.BE/VocaBuddy.Api/VocaBuddy.Api.csproj ./VocaBuddy.Api/
COPY VocaBuddy.BE/VocaBuddy.Application/VocaBuddy.Application.csproj ./VocaBuddy.Application/
COPY VocaBuddy.BE/VocaBuddy.Infrastructure/VocaBuddy.Infrastructure.csproj ./VocaBuddy.Infrastructure/
COPY VocaBuddy.BE/VocaBuddy.Domain/VocaBuddy.Domain.csproj ./VocaBuddy.Domain/
COPY VocaBuddy.Shared/VocaBuddy.Shared.csproj ../VocaBuddy.Shared/
RUN dotnet restore ./VocaBuddy.Api/VocaBuddy.Api.csproj
COPY VocaBuddy.BE/VocaBuddy.Api/. ./VocaBuddy.Api/
COPY VocaBuddy.BE/VocaBuddy.Application/. ./VocaBuddy.Application/
COPY VocaBuddy.BE/VocaBuddy.Infrastructure/. ./VocaBuddy.Infrastructure/
COPY VocaBuddy.BE/VocaBuddy.Domain/. ./VocaBuddy.Domain/
COPY VocaBuddy.Shared/. ../VocaBuddy.Shared/
RUN dotnet build VocaBuddy.Api/VocaBuddy.Api.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish VocaBuddy.Api/VocaBuddy.Api.csproj -c Release -o /app/publish

FROM base as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VocaBuddy.Api.dll"]