version: '3.9'

services:
  mssql:
    container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64/v8
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"

  identity:
    image: peterkovecses/identity
    build:
      context: ../src
      dockerfile: Identity/Dockerfile
    ports:
      - "5108:80"
      - "7121:443"
    environment:
      ASPNETCORE_URLS: "${ASPNETCORE_URLS}"
      ASPNETCORE_HTTPS_PORT: "${Identity_HTTPS_PORT}"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${Identity_Certificates_Password}"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "${Identity_Certificates_Path}"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  vocabuddy:
    image: peterkovecses/vocabuddy
    build:
      context: ../src
      dockerfile: VocaBuddy.BE/VocaBuddy.Api/Dockerfile
    ports:
      - "5063:80"
      - "7054:443"
    environment:
      ASPNETCORE_URLS: "${ASPNETCORE_URLS}"
      ASPNETCORE_HTTPS_PORT: "${VocaBuddyApi_HTTPS_PORT}"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${VocaBuddyApi_Certificates_Password}"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "${VocaBuddyApi_Certificates_Path}"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  vocabuddyui:
    image: peterkovecses/vocabuddyui
    build:
      context: ../src
      dockerfile: VocaBuddy.UI/Dockerfile
    ports:
      - "5101:80"
      - "7095:443"
    environment:
      ASPNETCORE_URLS: "${ASPNETCORE_URLS}"
      ASPNETCORE_HTTPS_PORT: "${VocaBuddyUI_HTTPS_PORT}"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${VocaBuddyUI_Certificates_Password}"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "${VocaBuddyUI_Certificates_Path}"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/