FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY Identity/Identity.csproj ./Identity/
COPY VocaBuddy.Shared/VocaBuddy.Shared.csproj ./VocaBuddy.Shared/
RUN dotnet restore ./Identity/Identity.csproj
COPY Identity/. ./Identity/
COPY VocaBuddy.Shared/. ./VocaBuddy.Shared/
RUN dotnet build Identity/Identity.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish Identity/Identity.csproj -c Release -o /app/publish

FROM base as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Identity.dll"]