# Stage 1: Build the Blazor WebAssembly application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copy csproj files and restore as distinct layers
COPY VocaBuddy.UI/VocaBuddy.UI.csproj ./VocaBuddy.UI/
COPY VocaBuddy.Shared/VocaBuddy.Shared.csproj ./VocaBuddy.Shared/
RUN dotnet restore ./VocaBuddy.UI/VocaBuddy.UI.csproj

# Copy everything else and build the application
COPY VocaBuddy.UI/. ./VocaBuddy.UI/
COPY VocaBuddy.Shared/. ./VocaBuddy.Shared/
WORKDIR /App/VocaBuddy.UI
RUN dotnet publish -c Release -o out

# Stage 2: Use Nginx to serve the static files with HTTPS support
FROM nginx AS nginx
WORKDIR /usr/share/nginx/html

# Copy static files from the build stage
COPY --from=build-env /App/VocaBuddy.UI/out/wwwroot .

# Copy nginx configuration
COPY VocaBuddy.UI/nginx.conf /etc/nginx/nginx.conf

# Copy SSL certificate and key
COPY ssl/server.crt /etc/nginx/ssl/server.crt
COPY ssl/server.key /etc/nginx/ssl/server.key

# Expose ports
EXPOSE 80
EXPOSE 443

# Set the default command to start nginx with HTTPS
CMD ["nginx", "-g", "daemon off;"]