FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/VocaBuddy.UI/VocaBuddy.UI.csproj VocaBuddy.UI/
COPY src/VocaBuddy.Shared/VocaBuddy.Shared.csproj VocaBuddy.Shared/
RUN dotnet restore VocaBuddy.UI/VocaBuddy.UI.csproj
COPY src/VocaBuddy.UI/ VocaBuddy.UI/
COPY src/VocaBuddy.Shared/ VocaBuddy.Shared/
RUN dotnet build VocaBuddy.UI/VocaBuddy.UI.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish VocaBuddy.UI/VocaBuddy.UI.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY src/VocaBuddy.UI/nginx.conf /etc/nginx/nginx.conf
COPY infra/ssl/server.crt /etc/nginx/ssl/server.crt
COPY infra/ssl/server.key /etc/nginx/ssl/server.key