version: '3.9'

services:
  mssql:
    container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64/v8
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Mypassword12"
    ports:
      - "1433:1433"